services:
  - type: web
    name: nectar-keeper
    runtime: docker
    dockerfilePath: keeper/Dockerfile
    dockerContext: keeper
    plan: free
    envVars:
      - key: KEEPER_SECRET
        sync: false
      - key: KEEPER_NAME
        value: keeper-alpha
      - key: REGISTRY_CONTRACT
        value: CAWT5HBM25OKGOMJHPFCXWXDWZ7FF436WXRKROTY2VW642FSKLYUKOUB
      - key: VAULT_CONTRACT
        value: CCXDLRE3IV5225LE3Z776KFB2VWD2MTXOJHAUKFA5RPYDJVOWCMHJ4U4
      - key: BLEND_POOL
        value: CADES3ASZGIK3DB54VWWASYOAHQB5OU2DBNGLGSJPAPCCY4Z5DHNOI7B
      - key: API_PORT
        value: "8080"
      - key: POLL_INTERVAL
        value: "10"
      - key: KNOWN_DEPOSITORS
        value: GB7LFWKR5NRENKX7EPE7LG3DYHQDRWR5PB732AX63B6MVMZMC7CXX6H7,GDRDWLE5A2TBTIVXDBJB5RH2CUVFNLUWSGPAZ32YBNWRKUDD4EOZWV5L,GDO2TLZOJMQQJWHFGO5HIY4TAU7OXJKFDT6IOJZWPJZNRCPCPA36FUSJ,GDCNLDY4BN3ULSCUD2CLODHPEW6D5G5DAZKVCSZB7MQTYGGFDZJWJKKT,GDCRIGIAALM5WLT3UQFDRPQU7EVN2PBWR6YDNMVEYB2OHROTBFOLL2VN,GBAVN7QBQKFRYBBCB57WT4GNMM4AAII7YMEUCIY3DB7FDGO6GKQEYN4A,GC3PCHZHFRCB2ZASUZXRZH3OXVI4B5EYQ5TXHCDD2EEHHMW3TN6HDJZM,GBPJRIJ5E43Z4IG7OTBWGQNOW5MY4RPTPYPAAB5ZKMVDBB2RXXQNZMQS,GCYITE7MIJMIOGNERURJAKBO7ELA5PNKIXZRHSQSVCSFUKKH6QHDE6KX,GDFLCTUHP5DW6AI2PC76PPBFEKYEPH2VCHSANDACO4JJCYTIKJ4SFSWS,GD3NX537IIZRAHCHV7JUCXBVMT55IFGHOOHIIAXGR2VKYJQ55KFFXP27,GAIN2XQ2VIIJBZ75P6TGEQR7HQMPBRUWNCDUO2HYZQAA5SRK4PAPPEVI,GAWCQESM3DOV6MZAJYXSBCQLJO2HJ72Y3UYQEFL3KURKQBJ4HHZAF76M,GDUD7QDYIM2H3GBKCJW7PD7PRFYSXOJLWWCZQW5JJMSBI4MCWLRWEMUX,GCUBGYBXCNREDUN6ZMO2EADUHZSNF76ULMOWEI5CQVNJ6MHCZ5EVYIT2,GASHYWLGY3XD4HSJWVV3COJKLT6WHQINC2J2FXO7C6AXQVWPW25RETUY,GDJEBRSBIE3BAXAMTK2XKSKMTOYD45PSRC4F5FEJAYM4EL6Y4WO23CGS,GAEUHW4ZVC656MRBJGN7B44UP6VYPAPI7HHYLGCRVP3E3GAPQG6ZZTDU
    healthCheckPath: /healthz
  - type: web
    name: nectar-keeper-beta
    runtime: docker
    dockerfilePath: keeper/Dockerfile
    dockerContext: keeper
    plan: free
    envVars:
      - key: KEEPER_SECRET
        sync: false
      - key: KEEPER_NAME
        value: keeper-beta
      - key: REGISTRY_CONTRACT
        value: CAWT5HBM25OKGOMJHPFCXWXDWZ7FF436WXRKROTY2VW642FSKLYUKOUB
      - key: VAULT_CONTRACT
        value: CCXDLRE3IV5225LE3Z776KFB2VWD2MTXOJHAUKFA5RPYDJVOWCMHJ4U4
      - key: BLEND_POOL
        value: CADES3ASZGIK3DB54VWWASYOAHQB5OU2DBNGLGSJPAPCCY4Z5DHNOI7B
      - key: API_PORT
        value: "8080"
      - key: POLL_INTERVAL
        value: "10"
      - key: KNOWN_DEPOSITORS
        value: GB7LFWKR5NRENKX7EPE7LG3DYHQDRWR5PB732AX63B6MVMZMC7CXX6H7,GDRDWLE5A2TBTIVXDBJB5RH2CUVFNLUWSGPAZ32YBNWRKUDD4EOZWV5L,GDO2TLZOJMQQJWHFGO5HIY4TAU7OXJKFDT6IOJZWPJZNRCPCPA36FUSJ,GDCNLDY4BN3ULSCUD2CLODHPEW6D5G5DAZKVCSZB7MQTYGGFDZJWJKKT,GDCRIGIAALM5WLT3UQFDRPQU7EVN2PBWR6YDNMVEYB2OHROTBFOLL2VN,GBAVN7QBQKFRYBBCB57WT4GNMM4AAII7YMEUCIY3DB7FDGO6GKQEYN4A,GC3PCHZHFRCB2ZASUZXRZH3OXVI4B5EYQ5TXHCDD2EEHHMW3TN6HDJZM,GBPJRIJ5E43Z4IG7OTBWGQNOW5MY4RPTPYPAAB5ZKMVDBB2RXXQNZMQS,GCYITE7MIJMIOGNERURJAKBO7ELA5PNKIXZRHSQSVCSFUKKH6QHDE6KX,GDFLCTUHP5DW6AI2PC76PPBFEKYEPH2VCHSANDACO4JJCYTIKJ4SFSWS,GD3NX537IIZRAHCHV7JUCXBVMT55IFGHOOHIIAXGR2VKYJQ55KFFXP27,GAIN2XQ2VIIJBZ75P6TGEQR7HQMPBRUWNCDUO2HYZQAA5SRK4PAPPEVI,GAWCQESM3DOV6MZAJYXSBCQLJO2HJ72Y3UYQEFL3KURKQBJ4HHZAF76M,GDUD7QDYIM2H3GBKCJW7PD7PRFYSXOJLWWCZQW5JJMSBI4MCWLRWEMUX,GCUBGYBXCNREDUN6ZMO2EADUHZSNF76ULMOWEI5CQVNJ6MHCZ5EVYIT2,GASHYWLGY3XD4HSJWVV3COJKLT6WHQINC2J2FXO7C6AXQVWPW25RETUY,GDJEBRSBIE3BAXAMTK2XKSKMTOYD45PSRC4F5FEJAYM4EL6Y4WO23CGS,GAEUHW4ZVC656MRBJGN7B44UP6VYPAPI7HHYLGCRVP3E3GAPQG6ZZTDU
    healthCheckPath: /healthz
