#!/usr/bin/env bash
# gen-wallets.sh — Generate 18 Stellar keypairs (1 admin + 2 keepers + 15 users)
# Outputs: .env.wallets (secrets, NOT committed) and wallets.json (human-readable)
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"

# Require stellar CLI
if ! command -v stellar &>/dev/null; then
  echo "ERROR: 'stellar' CLI not found. Install from https://developers.stellar.org/docs/tools/developer-tools" >&2
  exit 1
fi

OUTPUT_ENV="$ROOT_DIR/.env.wallets"
OUTPUT_JSON="$ROOT_DIR/wallets.json"

echo "Generating 18 keypairs..."

generate_keypair() {
  # stellar keys generate returns a key name; we use generate-random output
  local output
  output=$(stellar keys generate --no-fund --quiet "tmp-$$-${RANDOM}" 2>/dev/null || true)

  # Fall back to python/node if stellar CLI doesn't support bare generate
  # Use stellar-sdk or raw keypair generation
  node -e "
const { Keypair } = require('@stellar/stellar-sdk');
const kp = Keypair.random();
console.log(kp.secret() + ' ' + kp.publicKey());
" 2>/dev/null || python3 -c "
from stellar_sdk import Keypair
kp = Keypair.random()
print(kp.secret + ' ' + kp.public_key)
" 2>/dev/null
}

# Generate keypairs using node (stellar-sdk) or python
if command -v node &>/dev/null && node -e "require('@stellar/stellar-sdk')" 2>/dev/null; then
  GEN_CMD="node"
elif command -v python3 &>/dev/null && python3 -c "from stellar_sdk import Keypair" 2>/dev/null; then
  GEN_CMD="python3"
else
  echo "ERROR: Need node (@stellar/stellar-sdk) or python3 (stellar-sdk) to generate keypairs" >&2
  echo "Install: npm install -g @stellar/stellar-sdk  OR  pip install stellar-sdk" >&2
  exit 1
fi

gen_keypair_node() {
  node -e "
const { Keypair } = require('@stellar/stellar-sdk');
const kp = Keypair.random();
process.stdout.write(kp.secret() + ' ' + kp.publicKey() + '\n');
"
}

gen_keypair_python() {
  python3 -c "
from stellar_sdk import Keypair
kp = Keypair.random()
print(kp.secret + ' ' + kp.public_key)
"
}

gen_pair() {
  if [ "$GEN_CMD" = "node" ]; then
    gen_keypair_node
  else
    gen_keypair_python
  fi
}

# Generate all keypairs
echo "Using $GEN_CMD for keypair generation"

read ADMIN_SECRET ADMIN_ADDRESS <<< $(gen_pair)
read KEEPER_A_SECRET KEEPER_A_ADDRESS <<< $(gen_pair)
read KEEPER_B_SECRET KEEPER_B_ADDRESS <<< $(gen_pair)

USER_SECRETS=()
USER_ADDRESSES=()
for i in $(seq 1 15); do
  read SECRET ADDRESS <<< $(gen_pair)
  USER_SECRETS+=("$SECRET")
  USER_ADDRESSES+=("$ADDRESS")
done

# Write .env.wallets
cat > "$OUTPUT_ENV" <<EOF
# Auto-generated by gen-wallets.sh — DO NOT COMMIT
ADMIN_SECRET=${ADMIN_SECRET}
ADMIN_ADDRESS=${ADMIN_ADDRESS}

KEEPER_A_SECRET=${KEEPER_A_SECRET}
KEEPER_A_ADDRESS=${KEEPER_A_ADDRESS}

KEEPER_B_SECRET=${KEEPER_B_SECRET}
KEEPER_B_ADDRESS=${KEEPER_B_ADDRESS}

EOF

for i in $(seq 1 15); do
  IDX=$((i-1))
  NUM=$(printf "%02d" $i)
  echo "USER_${NUM}_SECRET=${USER_SECRETS[$IDX]}" >> "$OUTPUT_ENV"
  echo "USER_${NUM}_ADDRESS=${USER_ADDRESSES[$IDX]}" >> "$OUTPUT_ENV"
done

# Write wallets.json
{
  echo "{"
  echo "  \"admin\": {\"secret\": \"${ADMIN_SECRET}\", \"address\": \"${ADMIN_ADDRESS}\"},"
  echo "  \"keeper_alpha\": {\"secret\": \"${KEEPER_A_SECRET}\", \"address\": \"${KEEPER_A_ADDRESS}\"},"
  echo "  \"keeper_beta\": {\"secret\": \"${KEEPER_B_SECRET}\", \"address\": \"${KEEPER_B_ADDRESS}\"},"
  echo "  \"users\": ["
  for i in $(seq 1 15); do
    IDX=$((i-1))
    COMMA=","
    [ $i -eq 15 ] && COMMA=""
    echo "    {\"secret\": \"${USER_SECRETS[$IDX]}\", \"address\": \"${USER_ADDRESSES[$IDX]}\"}${COMMA}"
  done
  echo "  ]"
  echo "}"
} > "$OUTPUT_JSON"

echo ""
echo "Generated wallets:"
echo "  Admin:     ${ADMIN_ADDRESS}"
echo "  Keeper A:  ${KEEPER_A_ADDRESS}"
echo "  Keeper B:  ${KEEPER_B_ADDRESS}"
for i in $(seq 1 15); do
  NUM=$(printf "%02d" $i)
  IDX=$((i-1))
  echo "  User ${NUM}:   ${USER_ADDRESSES[$IDX]}"
done
echo ""
echo "Written to: $OUTPUT_ENV (secrets — DO NOT COMMIT)"
echo "Written to: $OUTPUT_JSON"
